version: '3'
services:
  qiling:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/home/logs/
      - ./results:/home/results/
      - ./coverage:/home/coverage/
    working_dir: /home
    command: ./qiling/run_qiliot.sh